version: '3.8'

services: 
  db: 
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports: 
      - "${DB_PORT_EXTERNAL}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${DB_HOST}", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: app-estoque
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
volumes:
  db_data: